# Valores personalizados para nuestra plataforma
replicaCount: 0

image:
  repository: mvega0911/devops-platform
  tag: "latest"
  pullPolicy: Always

config:
  env: "dev"
  appName: "DevOps Platform Demo V1.2"

secret:
  key: "c3VwZXJzZWNyZXRrZXkxMjM="

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30001