apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: devops-platform
    # Esta etiqueta es vital para que Prometheus lo detecte automáticamente
    release: monitoring 
spec:
  type: {{ .Values.service.type }}
  selector:
    # Asegúrate de que este label coincida exactamente con el de tu deployment.yaml
    app: {{ .Release.Name }} 
  ports:
    - name: http-metrics # Ponerle nombre al puerto es obligatorio para Grafana/Prometheus
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}