apiVersion: v1
kind: Service
metadata:
  name: devops-platform
spec:
  selector:
    app: devops-platform
  ports:
    - nodePort: 30001 #Puerto del Host/Nodo por donde el servicio NodePort sera accesible
      port: 80 #Puerto del servicio en este caso NodePort
      targetPort: 8000 #Puerto de los Pods Objetivos
  type: NodePort
